server:
  port: 8100


spring:
  application:
    name: pks
  datasource:
    url: jdbc:mysql://localhost:3306/pks
    username: root
    password: sWQ6zgU4ofWw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


  flyway:
    enabled: true
  ai:
    ollama:
      init:
        pull-model-strategy: never
      base-url: http://localhost:11434
      chat:
        options:
          model: "Emilly"
